### ISSUE TITLE
10.10pm shown at 9:10pm

### ISSUE THREAD

**Issue by prattmic** [JohannesNE/literature-clock#1]
I love this clock, but happened to open it at 9:10pm, when there is a data issue:

`21:10|10.10pm.|10.10pm. When you turn your recorder on you must adjust clock and the calendar.......Press red and nothing happens. Press numbers and nothing happens. Wish stupid video had never been invented.|Bridget Jones's Diary |Helen Fielding`

21:10 is 9:10pm, not 10:10pm.

**Comment by JohannesNE** [comment]
Thanks for the catch :)
