### ISSUE TITLE
Question: How would you update the quotes?

### ISSUE THREAD

**Issue by marshalmiller** [JohannesNE/literature-clock#21]
How do you update or add quotes? Could you do it just in the CSV file or do you need to adjust the JSON files as well?

**Comment by JohannesNE** [comment]
You should only edit the .csv manually. The json is updated by the R script. 
If you do not use R, you can just make a pull request with an updated csv, then I'll add the output from the R script.

**Comment by marshalmiller** [comment]
OK. Awesome. Thank you. I just didn't want trial and error and break everything. Thank you again.

**Comment by srosebattles** [comment]
I just found this project and have quotes that I'd like to contribute. I cloned the project and made a few additions to the csv on a new branch, but when I try to push that branch I get a "permission denied" message. May I have access to the repo?
