### ISSUE TITLE
Possible fix for "Illegal quoting in line 2"

### ISSUE THREAD

**Issue by SkabbMask** [JohannesNE/literature-clock#28]
I'm not sure where this error lies. But I wanted the csv as json from the start so did some regex, and thought to share in case it is of any use :) Also attaching the result I got.

1. Remove the " from beginning and end of quote:
Search+Replace
|" -> |
"| -> |

2. Escape all ":
Search+Replace
"" -> \"

3. Add break at end

4. To json:
Regex Search+Replace
([0-9]+:[0-9]+)\|([^|]+)\|([^|]+)\|([^|]+)\|([^|]+)\|([^|]+)\n
{"time":"$1","timeInQuote":"$2","quote":"$3","title":"$4","author":"$5"},

5. Remove the last ,
6. Encapsulate all in []
7. Escape breaks:
Search+Replace
\n -> \\n

[csvjson.txt](https://github.com/JohannesNE/literature-clock/files/8455117/csvjson.txt)

**Comment by JohannesNE** [comment]
Where/when do you experience the error? 

JSON is probably a better choice for a file that is supposed to be human editable.

Thank you for sharing. For now, I will continue to generate the formatted JSONs  from the csv, as it allows any quote fixes / additions to be easily used in the [Kindle literature clock](https://www.instructables.com/Literary-Clock-Made-From-E-reader/) as well.

**Comment by SkabbMask** [comment]
I got a similar error when I tried converting the csv into json manually as is. But haven't seen the error myself in this project, was only referring to the description in the csv file at the top (see attachement), about making it searchable.
![Capture](https://user-images.githubusercontent.com/9406559/162576649-0202927e-6b36-4c15-943c-c8c189aa4fe6.PNG)

**Comment by darthshittious** [comment]
This is not an error with the dataset. GitHub only officially supports pretty rendering of tab and comma separated values.  
Using `|` as a separator seems to trip the parser up for some reason, though it tries its best to work.

(also FWIW regex is *probably* the wrong tool for this)

**Comment by JohannesNE** [comment]
Agreed. I'll close the issue, but thank you @SkabbMask for reaching out. .json would probably be a better format for the "raw" quotes, but I believe compatibility with the Kindle project is a nice feature.

**Comment by ikornaselur** [comment]
@JohannesNE: Out of curiosity, is the Kindle project maintained somewhere, where you pull updates from, or do you just mean compatibility to the original project so that in theory you could just switch the files out?

Mainly just curiosity on my end if there is some further source where the quotes are being updates, as I maintain a CLI tool ([litime](https://github.com/ikornaselur/litime)) to display the quotes based on the current time in your terminal and I do pull in the updates you publish here, though I then take the json files and further transform them into just a static rust source file that I then use!

**Comment by JohannesNE** [comment]
That is a very nice project! I do not believe that the kindle project is publicly maintained. I just like that the additions people make to the quotes here, could (theoretically) be added to the Kindle project.
