### ISSUE TITLE
Duplicated quotes

### ISSUE THREAD

**Issue by srosebattles** [JohannesNE/literature-clock#32]
A number of quotes are the same, just cut slightly different with more or less text. Is this intended/desired? 
e.g.
```00:00|twelve|Bernardo: 'Tis now struck twelve; get thee to bed, Francisco.|Hamlet |Shakespeare|unknown```
```00:00|twelve|Francisco. You come most carefully upon your hour. Bernardo. 'Tis now struck twelve. Get thee to bed, Francisco.|Hamlet |William Shakespeare|unknown```

**Comment by JohannesNE** [comment]
This is not intended. 
In this case I prefer nr two, but with the punctuation from nr 1 :shrug: 
I do not have a strong opinion on this though.

Thank you very much for your PR (https://github.com/JohannesNE/literature-clock/pull/33/commits)
I will look though it and generate the .json files ASAP.

**Comment by srosebattles** [comment]
I think a lot of these duplicates were introduced with https://github.com/JohannesNE/literature-clock/pull/29.
I'd be happy to go through and do some editing if you haven't already started doing that. I'll put it up as a separate PR, though.

**Comment by JohannesNE** [comment]
Ahh, that seems likely.

That would be very helpful. I do not have much extra time ATM.

**Comment by JohannesNE** [comment]
fixed in #34
