### ISSUE TITLE
Generated json files are malformed

### ISSUE THREAD

**Issue by ikornaselur** [JohannesNE/literature-clock#36]
Unfortunately the run of the R script from #34 has introduced malformed json output, specifically sections such as:

https://github.com/JohannesNE/literature-clock/blob/6a0a6a84fc499f2e254fec5f2259db7b593c842d/docs/times/01_30.json#L33
https://github.com/JohannesNE/literature-clock/blob/6a0a6a84fc499f2e254fec5f2259db7b593c842d/docs/times/02_04.json#L6
https://github.com/JohannesNE/literature-clock/blob/6a0a6a84fc499f2e254fec5f2259db7b593c842d/docs/times/03_00.json#L438
https://github.com/JohannesNE/literature-clock/blob/6a0a6a84fc499f2e254fec5f2259db7b593c842d/docs/times/11_30.json#L69
https://github.com/JohannesNE/literature-clock/blob/6a0a6a84fc499f2e254fec5f2259db7b593c842d/docs/times/13_20.json#L15
https://github.com/JohannesNE/literature-clock/blob/6a0a6a84fc499f2e254fec5f2259db7b593c842d/docs/times/18_04.json#L6

it seems that the value has multiple entries within it. They should be simple to find by grepping for `|` within the json files. Looks like it could be an incorrect delimiter handling somehow?

**Comment by JohannesNE** [comment]
Thank you. I overlooked this. Opened a new issue related to this, with the intend of making the csv simpler to edit.

https://github.com/JohannesNE/literature-clock/issues/38
