### ISSUE TITLE
NSFW tag not accurately filtering quotes manually marked as nsfw

### ISSUE THREAD

**Issue by srosebattles** [JohannesNE/literature-clock#42]
I had the clock up and running in a browser window with the NSFW filter active and the following quote still appeared:

```14:43|2.43pm|Jacobson died at 2.43pm the next day after slashing his wrists with a razor blade in the second cubicle from the left in the men's washroom on the third floor.|Now: Zero|JG Ballard|nsfw```

I've been switching back and forth between SFW/NSFW and thought I was seeing this, this was the first one that I was sure both that I had the filter on and that the quote was one I had marked as nsfw.

**Comment by JohannesNE** [comment]
I cannot reproduce this. You can test this specifically by uncommenting 
https://github.com/JohannesNE/literature-clock/blob/8cd717185d5f53e1555a2c2b8aa4a298a56def53/docs/index.html#L110

and setting the time to the time you want to test (e.g. 14:43:00).

**Comment by JohannesNE** [comment]
You can may be able to run index.html directly in your browser. Otherwise, run `python3 -m http.server` in `docs/` and open the local server in a browser.
