### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JohannesNE** [JohannesNE/literature-clock#61]
Received on Twitter:

It was exactly fourteen minutes past midnight when he completed the final call. Among the men he had reched were honourable men. Their voices would be heard by the President.  

I expect this is meant to be 'reached'.  Thought you might want to know to fix it up.

**Comment by ItsAJ1005** [comment]
This issue is already resolved, please close it :)

<img width="572" alt="image" src="https://github.com/JohannesNE/literature-clock/assets/122255411/09a466fa-8adf-415f-a8d8-2768cf398c07">
