### ISSUE TITLE
How can you change the display size?

### ISSUE THREAD

**Issue by nakitadog** [JohannesNE/literature-clock#9]
I noticed that you are using viewport vw for the font size as well as an equation to dynamically size the literary quote.

Is there a way to make it so that the display will fill a container of 600px X 800px?

I'm interested in modifying the code so that I can export the literary quotes as individual images in order to pass over to the Kindle.

**Comment by nakitadog** [comment]
That's actually why I was asking. 

That download that he provides in his instructions does not contain as many literary quotes you have. He does not have a full 1,440 minutes. You seem to have all minutes and alternatives for some minutes. 

I wanted a way to loop through all of your quotes and generate the images so I can push them to my Kindle clock that I created based on that particular instructable. 

The issue I keep running into is CSS and getting everything to fit in 600px X 800px.

**Comment by JohannesNE** [comment]
The dataset in the project is based entirely on the Kindle project. I have just filled empty minutes with the latest quote, so the clock is a few minutes slow at some points. 

To answer your question I do not have a specific solution, but I'm sure you can make it fit by fiddling with the values in the script. I did it by finding the vw that worked best for many screen sizes for different lengths of text, an then fitted at 3rd order polynomial to it.

**Comment by nakitadog** [comment]
Okay thank you.
